### ISSUE TITLE
tests fail to build with 1.5.28-165-gc11da76

### ISSUE THREAD

**Issue by GoogleCodeExporter** [austin987/win16test#2]
```
[austin@localhost src]$ make all
wine wcc -D_X86_ -DSTANDALONE '-i=C:\WATCOM\h\win;C:\WATCOM\h'-zW -e25 -zq -od 
-d2 -w4 -wcd=126 -wcd=102 -wcd=112 -bw-bt=windows  alloc.c
alloc.c(83): Error! E1010: Type mismatch
alloc.c(83): Error! E1151: Parameter count does not agree with previous 
definition
alloc.c(83): Note! N2002: 'winetest_ok' defined in: test.h(272)
...
```

Original issue reported on code.google.com by `austinenglish@gmail.com` on 24 Apr 2013 at 5:31
